routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\CasillaController;
use App\Http\Controllers\CandidatoController;
use App\Http\Controllers\FuncionarioController;
use App\Http\Controllers\RolController;
use App\Http\Controllers\EleccionController;
use App\Http\Controllers\EleccioncomiteController;
use App\Http\Controllers\VotoController;
use App\Http\Controllers\ImeiautorizadoController;
use App\Http\Controllers\FuncionariocasillaController;
use App\Http\Controllers\VotocandidatoController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

//PDF TABLAS
Route::get('casilla/pdf', [CasillaController::class, 'generatepdf']);
Route::get('candidato/pdf', [CandidatoController::class, 'generatepdf']);
Route::get('eleccion/pdf', [EleccionController::class, 'generatepdf']);
Route::get('funcionario/pdf', [FuncionarioController::class, 'generatepdf']);
Route::get('rol/pdf', [RolController::class, 'generatepdf']);
Route::get('eleccioncomite/pdf', [EleccioncomiteController::class, 'generatepdf']);
Route::get('voto/pdf', [VotoController::class, 'generatepdf']);
Route::get('imeiautorizado/pdf', [ImeiautorizadoController::class, 'generatepdf']);
Route::get('funcionariocasilla/pdf', [FuncionariocasillaController::class, 'generatepdf']);
Route::get('votocandidato/pdf', [VotocandidatoController::class, 'generatepdf']);

//GRAFICAS
Route::get('votocandidato/chart', [VotocandidatoController::class, 'generatechart']);
Route::get('funcionario/chart', [FuncionarioController::class, 'generatechart']);
Route::get('candidato/chart', [CandidatoController::class, 'generatechart']);


//CONTROLLERS
Route::resource('casilla', CasillaController::class);
Route::resource('candidato', CandidatoController::class);
Route::resource('funcionario', FuncionarioController::class);
Route::resource('rol', RolController::class);
Route::resource('eleccion', EleccionController::class);
Route::resource('eleccioncomite', EleccioncomiteController::class);
Route::resource('voto', VotoController::class);
Route::resource('imeiautorizado', ImeiautorizadoController::class);
Route::resource('funcionariocasilla', FuncionariocasillaController::class);
Route::resource('votocandidato', VotocandidatoController::class);

app/Models/Candidato.php
<?php

/**
 * Created by Reliese Model.
 */

namespace App\Models;

use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;

/**
 * Class Candidato
 * 
 * @property int $id
 * @property string $nombrecompleto
 * @property string|null $foto
 * @property string|null $sexo
 * @property string|null $perfil
 * 
 * @property Collection|Voto[] $votos
 *
 * @package App\Models
 */
class Candidato extends Model
{
	protected $table = 'candidato';
	public $timestamps = false;

	protected $fillable = [
		'nombrecompleto',
		'foto',
		'sexo',
		'perfil'
	];

	public function votos()
	{
		return $this->belongsToMany(Voto::class, 'votocandidato')
					->withPivot('votos');
	}
}

app/Http/Controllers/Api/CandidatoController.php
<?php

namespace App\Http\Controllers\Api;
use App\Http\Controllers\Api\GenericController as GenericController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use App\Models\Candidato;

class CandidatoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $candidatos = Candidato::all();
        $resp = $this->sendResponse($candidatos, "Listado de candidatos");
        return ($resp);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validacion = Validator::make($request->all(), [
        	'nombrecompleto' => 'unique:candidato|required|max:200',
        	'sexo' =>'required'
        ]);

        if ($validacion->fails())
        	return $this->sendError("Error de validacion", $validacion->errors());
            $foto="";
            $perfil="";
        if ($request->hasFile('foto')){
        	$foto = $request->file('foto');
        	$foto= $foto->getClientOriginalName();
        }

        if ($request->hasFile('perfil')){
        	$perfil = $request->file('perfil');
        	$perfil = $perfil->getClientOriginalName();
        }

        $campos = array(
        	'nombrecompleto' => $request->nombrecompleto,
        	'sexo' => $request->sexo,
        	'foto' => $foto,
        	'perfil' => $perfil
        );

        if ($request->hasFile('foto')) $foto->move(public_path('img'), $foto);
        if ($request->hasFile('perfil')) $perfil->move(public_path('pdf'), $perfil);
        $candidato = Candidato::create($campos);
        $resp = $this->sendResponse($candidato,
        	"Guardado...");
        return($resp);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/CandidatoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Candidato;
use Illuminate\Support\Facades\DB;
use Barryvdh\DomPDF\Facade as PDF; //--- Se agregó esta línea

class CandidatoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $candidatos = Candidato::all();
    return view('candidato/list', compact('candidatos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('candidato/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $foto ="";
        $perfil ="";

        $request->validate([
        'nombrecompleto' => 'required|max:200',
        'sexo' => 'required|max:1',
        'foto' => 'required|mimes:jpeg,png,jpg,gif,svg|max:2048',
        'perfil' => 'required',
        ]);

        if ($request->hasFile('foto')){
           $foto = $request->foto->getClientOriginalName();
           $request->foto->move(public_path('uploads'), $foto);
        }

        if($request->hasFile('perfil')){
           $perfil = $request->perfil->getClientOriginalName();
           $request->perfil->move(public_path('uploads'), $perfil);
        }

        $data=[
          "nombrecompleto" => $request->nombrecompleto,
          "sexo" => $request->sexo,
          "foto" => $foto,
          "perfil" => $perfil
    ];

        $candidato = Candidato::create($data);
        return redirect('candidato')->with('success',
        $candidato->nombrecompleto . ' guardado satisfactoriamente ...');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $candidato = Candidato::find($id);
        return view('candidato/edit', compact('candidato'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
       $foto ="";
        $perfil ="";

        $request->validate([
        'nombrecompleto' => 'required|max:200',
        'sexo' => 'required|max:1',
        'foto' => 'required|mimes:jpeg,png,jpg,gif,svg|max:2048',
        'perfil' => 'required',
        ]);

        if($request->hasFile('foto')){
           $foto = $request->foto->getClientOriginalName();
           $request->foto->move(public_path('uploads'), $foto);
        }

        if($request->hasFile('perfil')){
           $perfil = $request->perfil->getClientOriginalName();
           $request->perfil->move(public_path('uploads'), $perfil);
        }

        $data=[
          "nombrecompleto" => $request->nombrecompleto,
          "sexo" => $request->sexo,
          "foto" => $foto,
          "perfil" => $perfil
    ];

        Candidato::find($id)->update($data);
        return redirect('candidato')->with('success',
        $data["nombrecompleto"] . ' Actulizado correctamente ...'); 
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Candidato::find($id)->delete();
        return redirect('candidato');
    }

    public function generatepdf()
    {
         //echo "prueba";
        $candidatos = Candidato::all();
       //print_r($candidatos);
       $pdf = PDF::loadView('candidato/vista', ['candidatos'=>$candidatos]);
       return $pdf->stream('candidatos.pdf');
    }

    /*public function generatechart()
    {
        
        $sql = "SELECT sexo, COUNT(*) FROM candidato GROUP BY sexo";
        $candidatos = DB::select($sql);
        return view("candidato/chart",
            compact("candidatos"));
    
     }*/

     public function generatechart()
    {
       // $sql = "SELECT candidato_id , votos FROM votocandidato GROUP BY candidato_id";
       // $sql ="SELECT votos,candidato_id FROM votocandidato";

        $sql = "SELECT sexo, count(*) AS TOTAL FROM candidato group by sexo";
        $candidatos = DB::select($sql);
        return view("candidato/chart",['candidatos'=>$candidatos]);
     }

     
}

resources/views/candidato/chart.blade.php
@extends('plantilla')
@section('title','Panel de control')
@section('content')

<html>
  <head>

    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
      google.charts.load('current', {'packages':['corechart']});
      google.charts.setOnLoadCallback(drawChart);

      function drawChart() {

        var data = google.visualization.arrayToDataTable([
          ['candidato', 'Total'],
          @foreach ($candidatos as $candidatos)
          ['Sexo:{{$candidatos->sexo}}',{{$candidatos->TOTAL}}],
          @endforeach
        ]);

        var options = {
          title: 'Gráfica de Genero de Candidatos'
        };

        var chart = new google.visualization.PieChart(document.getElementById('piechart'));

        chart.draw(data, options);
      }
    </script>
  </head>
  <body>
    <div id="piechart" style="width: 1000px; height: 500px;"></div>
  </body>
</html>

@endsection

resources/views/candidato/create.blade.php
@extends('plantilla')
@section('content')
<style>
	.uper {
		margin-top: 40px;
	}
</style>
<div class="card uper">
	<div class="card-header">
	Agregar Candidato
	</div>
	<div class="card-body">
		@if ($errors->any())
		<div class="alert alert-danger">
			<ul>
				@foreach ($errors->all() as $error)
				<li>{{ $error }}</li>
				@endforeach
			</ul>
		</div><br />
		@endif
		<form method="post" action="{{ route('candidato.store') }} " enctype="multipart/form-data">
			{{ csrf_field() }}

			<div class="form-group">
				@csrf
				<label for="nombrecompleto">Nombre:</label>

				<input type="text" class="form-control" name="nombrecompleto" id="nombrecompleto" />

			</div>
			<div class="form-group">
				@csrf
				<label for="foto">Foto:</label>
				<input type="file" class="form-control" name="foto" id="foto" />
			</div>

			<div class="form-group">
				@csrf
				<label for="sexo">Sexo:</label>
				<select name="sexo">
					<option value="H">Hombre</option>
					<option value="M">Mujer</option>
				</select>
			</div>

			<div class="form-group">
				@csrf
				<label for="perfil">Perfil:</label>
				<input type="file" class="form-control" name="perfil" id="perfil" />
			</div>

			<button type="submit" class="btn btn-primary"onClick="return validate ()">Guardar</button>

		</form>
	</div>
</div>
@endsection

@section('page-script')
    <script type="text/javascript" src="/js/candidato.js"></script>
@stop

resources/views/candidato/edit.blade.php
@extends('plantilla')
@section('content')
<style>
	.uper {
	margin-top: 40px;
}
</style>

<div class="card">
	<div class="card-header">
		Editar candidato
	</div>	
<div class="card-body">
	@if ($errors->any())
		<div class="alert alert-danger">
			<ul>
				@foreach ($errors->all() as $error)
				<li>{{ $error }}</li>
				@endforeach
			</ul>
		</div><br />
	@endif
	<form method="POST"
		action="{{ route('candidato.update', $candidato->id) }}"
		enctype="multipart/form-data">
		{{ csrf_field() }}
		@method('PUT')
		<div class="form-group">
		@csrf
		<label for="id">ID:</label>
		<input type="text"
			class="form-control"
			readonly="true"
			value="{{$candidato->id}}"
			name="id"/>
		</div>
		<div class="form-group">
			@csrf
			<label for="nombrecompleto">Nombre Completo:</label>
			<input type="text"
			value="{{$candidato->nombrecompleto}}"
			class="form-control"
			name="nombrecompleto"/>
		</div>
		<div class="form-group">
			@csrf
			<label for="sexo">Sexo:</label>
			<select name="sexo" class="form-control" value="{{$candidato->sexo}}">
				<option value="H" <?echo (($candidato->sexo=='H')? 'selected':'');?> >Hombre</option>
				<option value="M" <?echo (($candidato->sexo=='M')? 'selected':'');?> >Mujer</option>
			</select>
		</div>

		<div class="form-group">
			<label for="foto">Elija la foto del candidato</label>
			<input type="file" class="form-control" name="foto">
		</div>

		<div class="form-group">
			<label for="perfil">Elija el documento sobre el perfil</label>
			<input type="file" class="form-control" name="perfil">
		</div>
		<button type="submit" class="btn btn-primary">Guardar</button>
	</form>
	</div>
</div>
@endsection

resources/views/candidato/list.blade.php
@extends('plantilla')
@section('content')
<style>
	.uper {
		margin-top: 40px;
	}
</style>

<br>
<br>
<h1 align="center">CANDIDATOS</h1>
<br>

<div class="uper">
	@if(session()->get('success'))
	<div class="alert alert-success">
		{{ session()->get('success') }}
	</div><br />
	@endif
	<table class="table table-striped">
		<thead>
			<tr>
				<th>ID</th>
				<th>NOMBRE</th>
				<th>FOTO</th>
				<th>PERFIL</th>
				<th>SEXO</th>
				<th colspan="2">Action</th>
			</tr>
		</thead>
		<tbody>
			@foreach($candidatos as $candidato)
			<tr>
				<td>{{$candidato->id}}</td>
				<td>{{$candidato->nombrecompleto}}</td>
				<td><img src="uploads/{{$candidato->foto}}" width="150" height="150" alt="aqui va la foto"></td>
				<td><a href="uploads/{{$candidato->perfil}}">
					<img src="uploads/icon-pdf.svg" alt="pdf" width="150" height="150"></a>
				</td>
				<td>{{$candidato->sexo}}</td>

				<td><a href="{{ route('candidato.edit', $candidato->id)}}"
					class="btn btn-primary">Edit</a></td>
				<td>
					<form action="{{ route('candidato.destroy', $candidato->id)}}" method="post">
						@csrf
						@method('DELETE')
						<button class="btn btn-danger" type="submit"
						onclick="return confirm('Esta seguro de borrar a {{$candidato->nombrecompleto}}')" >Eliminar</button>
					</form>
				</td>
			</tr>
		@endforeach
	</tbody>
</table>
<div>
@endsection

resources/views/candidato/vista.blade.php
<!DOCTYPE HTML>
<HTML>
<head>
	<div style='text-align:center;'>	
   
		<h1>PDF generado desde etiquetas html:</h1>
		<h2> Candidato</h2>
		<br>
</head>
   
   </div>
   <BODY>
<table class="table table-striped" align="center" width="80%"  border="1" align="center" cellspacing="0">
		<thead>
			<tr>
				<th align="center">ID</th>
				<th align="center">NOMBRE</th>
				
				<th align="center"> SEXO</th>
		
			</tr>
		</thead>
		<tbody>
			@foreach($candidatos as $candidato)
			<tr>
				<td align="center">{{$candidato->id}}</td>
				<td>{{$candidato->nombrecompleto}}</td>
				
				<td align="center">{{$candidato->sexo}}</td>

				
			</tr>
		@endforeach
	</tbody>
</table>

<div>
	<div style='text-align:center;'>	
   
   		<h3>&copy;Wendy.dev</h3> 
</div>
<script type="text/php">
		if (isset($pdf) ) {
				$pdf->page_script('
				$font = $fontMetrics->get_font("Arial, Helvetica, sans-serif", "normal");
				$pdf->text(270, 730, "Pagina $PAGE_NUM de $PAGE_COUNT", $font, 10);
				');
		}
</script>
   </BODY>
</HTML>