routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\CasillaController;
use App\Http\Controllers\CandidatoController;
use App\Http\Controllers\FuncionarioController;
use App\Http\Controllers\RolController;
use App\Http\Controllers\EleccionController;
use App\Http\Controllers\EleccioncomiteController;
use App\Http\Controllers\VotoController;
use App\Http\Controllers\ImeiautorizadoController;
use App\Http\Controllers\FuncionariocasillaController;
use App\Http\Controllers\VotocandidatoController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

//PDF TABLAS
Route::get('casilla/pdf', [CasillaController::class, 'generatepdf']);
Route::get('candidato/pdf', [CandidatoController::class, 'generatepdf']);
Route::get('eleccion/pdf', [EleccionController::class, 'generatepdf']);
Route::get('funcionario/pdf', [FuncionarioController::class, 'generatepdf']);
Route::get('rol/pdf', [RolController::class, 'generatepdf']);
Route::get('eleccioncomite/pdf', [EleccioncomiteController::class, 'generatepdf']);
Route::get('voto/pdf', [VotoController::class, 'generatepdf']);
Route::get('imeiautorizado/pdf', [ImeiautorizadoController::class, 'generatepdf']);
Route::get('funcionariocasilla/pdf', [FuncionariocasillaController::class, 'generatepdf']);
Route::get('votocandidato/pdf', [VotocandidatoController::class, 'generatepdf']);

//GRAFICAS
Route::get('votocandidato/chart', [VotocandidatoController::class, 'generatechart']);
Route::get('funcionario/chart', [FuncionarioController::class, 'generatechart']);
Route::get('candidato/chart', [CandidatoController::class, 'generatechart']);


//CONTROLLERS
Route::resource('casilla', CasillaController::class);
Route::resource('candidato', CandidatoController::class);
Route::resource('funcionario', FuncionarioController::class);
Route::resource('rol', RolController::class);
Route::resource('eleccion', EleccionController::class);
Route::resource('eleccioncomite', EleccioncomiteController::class);
Route::resource('voto', VotoController::class);
Route::resource('imeiautorizado', ImeiautorizadoController::class);
Route::resource('funcionariocasilla', FuncionariocasillaController::class);
Route::resource('votocandidato', VotocandidatoController::class);

app/Models/Casilla.php
<?php

/**
 * Created by Reliese Model.
 */

namespace App\Models;

use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;

/**
 * Class Casilla
 * 
 * @property int $id
 * @property string $ubicacion
 * 
 * @property Collection|Funcionario[] $funcionarios
 * @property Collection|Imeiautorizado[] $imeiautorizados
 * @property Collection|Voto[] $votos
 *
 * @package App\Models
 */
class Casilla extends Model
{
	protected $table = 'casilla';
	public $timestamps = false;

	protected $fillable = [
		'ubicacion'
	];

	public function funcionarios()
	{
		return $this->belongsToMany(Funcionario::class, 'funcionariocasilla')
					->withPivot('id', 'rol_id', 'eleccion_id');
	}

	public function imeiautorizados()
	{
		return $this->hasMany(Imeiautorizado::class);
	}

	public function votos()
	{
		return $this->hasMany(Voto::class);
	}
}

app/Http/Controllers/Api/CasillaController.php
<?php

namespace App\Http\Controllers\Api;
use App\Http\Controllers\Api\GenericController as GenericController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use App\Models\Casilla;

class CasillaController extends GenericController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $casillas = Casilla::all();
        $resp = $this->sendResponse($casillas, "Listado de candidatos");
        return ($resp);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
         $validacion = Validator::make($request->all(), [
            'ubicacion' => 'unique:candidato|required|max:200',
        ]);

        $campos = array(
            'ubicacion' => $request->ubicacion,

        );

        $casilla = Casilla::create($campos);
        $resp = $this->sendResponse($casilla,
            "Guardado...");
        return($resp);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/CasillaController.php
<?php
namespace App\Http\Controllers;
use Illuminate\Http\Request;
use App\Models\Casilla;
use App\Charts\UserChart;
use ConsoleTVs\Charts\Classes\Chart;

use Barryvdh\DomPDF\Facade as PDF; //--- Se agregó esta línea
class CasillaController extends Controller
{
    /**
    * Display a listing of the resource.
    *
    * @return \Illuminate\Http\Response
    */
    public function index()
    {
        $casillas = Casilla::all();
        return view('casilla/list', compact('casillas'));
    }
    /**
    * Show the form for creating a new resource.
    *
    * @return \Illuminate\Http\Response
    */
    public function create()
    {
        return view('casilla/create');
    }
    /**
    * Store a newly created resource in storage.
    *
    * @param \Illuminate\Http\Request $request
    * @return \Illuminate\Http\Response
    */
    public function store(Request $request)
    {
        $validacion = $request->validate([
            'ubicacion' => 'required|max:100',
        ]);

        $casilla = Casilla::create($validacion);
        return redirect('casilla')->with('success',
        $casilla->ubicacion . ' guardado satisfactoriamente ...');
    }
    /**
    * Display the specified resource.
    *
    * @param int $id
    * @return \Illuminate\Http\Response
    */
    public function show($id)
    {
    //
    }
    /**
    * Show the form for editing the specified resource.
    *
    * @param int $id
    * @return \Illuminate\Http\Response
    */
    public function edit($id)
    {
        $casilla = Casilla::find($id);
        return view('casilla/edit',compact('casilla'));
    }
    /**
    * Update the specified resource in storage.
    *
    * @param \Illuminate\Http\Request $request
    * @param int $id
    * @return \Illuminate\Http\Response
    */
    public function update(Request $request, $id)
    {
        $validacion = $request->validate([
            'ubicacion' => 'required|max:100',
        ]);

        Casilla::whereId($id)->update($validacion);
        return redirect('casilla')
        ->with('success', 'Actualizado correctamente...');
    }
    /**
    * Remove the specified resource from storage.
    ** @param int $id
    * @return \Illuminate\Http\Response
    */
    public function destroy($id)
    {
        $casilla = Casilla::find($id);
        $casilla->delete();
        return redirect('casilla');
    }


   public function generatepdf()
    {
      $casillas = Casilla::all();
      // print_r($casillas);
        $pdf = PDF::loadView('casilla/vista', ['casillas'=>$casillas]);
        return $pdf->stream('casilla.pdf');
    }

} //--- end class

resources/views/casilla/create.blade.php
@extends('plantilla')
@section('content')
<style>
	.uper {
		margin-top: 40px;
	}
</style>
<div class="card uper">
	<div class="card-header">
		Agregar Casillas
	</div>
	<div class="card-body">
		@if ($errors->any())
		<div class="alert alert-danger">
			<ul>
				@foreach ($errors->all() as $error)
				<li>{{ $error }}</li>
			@endforeach
		</ul>
	</div><br />
	@endif
	<form method="post" action="{{ route('casilla.store') }} " enctype="multipart/form-data">
		{{ csrf_field() }}
		<div class="form-group">
			@csrf
			<label for="ubicacion">Ubicación:</label>
			<input type="text" class="form-control" name="ubicacion" id="ubicacion" />
		</div>
		<button type="submit" class="btn btn-primary"onClick="return validate ()">Guardar</button>
	</form>
</div>
</div>
@endsection


@section('page-script')
    <script type="text/javascript" src="/js/casilla.js"></script>
@stop

resources/views/casilla/edit.blade.php
@extends('plantilla')
@section('content')
<style>
	.uper {
		margin-top: 40px;
	}
</style>
<div class="card uper">
	<div class="card-header">	Editar casilla </div>
	<div class="card-body">
		@if ($errors->any())
		<div class="alert alert-danger">
			<ul>
				@foreach ($errors->all() as $error)
				<li>{{ $error }}</li>
			@endforeach
		</ul>
	</div><br />
	@endif
	<form method="POST" action="{{ route('casilla.update', $casilla->id) }}"
		enctype="multipart/form-data">
		{{ csrf_field() }}
		@method('PUT')
		<div class="form-group">
			@csrf
			<label for="id">ID:</label>
			<input type="text" class="form-control" readonly="true" value="{{$casilla->id}}"name="id"/>
		</div>
		<div class="form-group">
			@csrf
			<label for="descripcion">Ubicación:</label>
			<input type="text" value="{{$casilla->ubicacion}}" class="form-control" name="ubicacion"/>
		</div>
		<button type="submit" class="btn btn-primary">Guardar</button>
	</form>
</div>
</div>
@endsection

resources/views/casilla/list.blade.php
@extends('plantilla')
@section('content')
<style>
	.uper {
		margin-top: 40px;
	}
</style>

<br>
<br>
<h1 align="center">CASILLAS</h1>
<br>

<div class="uper">
	@if(session()->get('success'))
	<div class="alert alert-success">
		{{ session()->get('success') }}
	</div><br />
	@endif
	<table class="table table-striped">
		<thead>
			<tr>
				<td>ID</td>
				<td>UBICACION</td>
				<td colspan="2">Action</td>
			</tr>
		</thead>
		<tbody>
			@foreach($casillas as $casilla)
			<tr>
				<td>{{$casilla->id}}</td>
				<td>{{$casilla->ubicacion}}</td>
				<td><a href="{{ route('casilla.edit', $casilla->id)}}"
					class="btn btn-primary">Edit</a></td>
				<td>
					<form action="{{ route('casilla.destroy', $casilla->id)}}" method="post">
						@csrf
						@method('DELETE')
						<button class="btn btn-danger" type="submit"
						onclick="return confirm('Esta seguro de borrar {{$casilla->ubicacion}}')" >Del</button>
					</form>
				</td>
			</tr>
		@endforeach
	</tbody>
</table>
<div>
@endsection

resources/views/casilla/vista.blade.php
<!DOCTYPE HTML>
<HTML>
<head>
	<div style='text-align:center;'>	
		<h1>PDF generado desde etiquetas html:</h1>
		<h2> Casilla</h2><br>
</head>
   </div>
   <BODY>
      <table class="table table-striped" align="center" width="80%"  border="1" align="center" cellspacing="0">
		<thead>
			<tr>
				<td align="center">ID</td>
				<td align="center">UBICACION</td>
				
			</tr>
		</thead>
		<tbody>
			@foreach($casillas as $casilla)
			<tr>
				<td align="center">{{$casilla->id}}</td>
				<td>{{$casilla->ubicacion}}</td>
				
			</tr>
		@endforeach
	</tbody>
</table>
<div>
	<div style='text-align:center;'>	
   		<h3>&copy;Wendy.dev</h3> 
</div>
<script type="text/php">
		if (isset($pdf) ) {
				$pdf->page_script('
				$font = $fontMetrics->get_font("Arial, Helvetica, sans-serif", "normal");
				$pdf->text(270, 730, "Pagina $PAGE_NUM de $PAGE_COUNT", $font, 10);
				');
		}
</script>
   </BODY>
</HTML>