routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\CasillaController;
use App\Http\Controllers\CandidatoController;
use App\Http\Controllers\FuncionarioController;
use App\Http\Controllers\RolController;
use App\Http\Controllers\EleccionController;
use App\Http\Controllers\EleccioncomiteController;
use App\Http\Controllers\VotoController;
use App\Http\Controllers\ImeiautorizadoController;
use App\Http\Controllers\FuncionariocasillaController;
use App\Http\Controllers\VotocandidatoController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

//PDF TABLAS
Route::get('casilla/pdf', [CasillaController::class, 'generatepdf']);
Route::get('candidato/pdf', [CandidatoController::class, 'generatepdf']);
Route::get('eleccion/pdf', [EleccionController::class, 'generatepdf']);
Route::get('funcionario/pdf', [FuncionarioController::class, 'generatepdf']);
Route::get('rol/pdf', [RolController::class, 'generatepdf']);
Route::get('eleccioncomite/pdf', [EleccioncomiteController::class, 'generatepdf']);
Route::get('voto/pdf', [VotoController::class, 'generatepdf']);
Route::get('imeiautorizado/pdf', [ImeiautorizadoController::class, 'generatepdf']);
Route::get('funcionariocasilla/pdf', [FuncionariocasillaController::class, 'generatepdf']);
Route::get('votocandidato/pdf', [VotocandidatoController::class, 'generatepdf']);

//GRAFICAS
Route::get('votocandidato/chart', [VotocandidatoController::class, 'generatechart']);
Route::get('funcionario/chart', [FuncionarioController::class, 'generatechart']);
Route::get('candidato/chart', [CandidatoController::class, 'generatechart']);


//CONTROLLERS
Route::resource('casilla', CasillaController::class);
Route::resource('candidato', CandidatoController::class);
Route::resource('funcionario', FuncionarioController::class);
Route::resource('rol', RolController::class);
Route::resource('eleccion', EleccionController::class);
Route::resource('eleccioncomite', EleccioncomiteController::class);
Route::resource('voto', VotoController::class);
Route::resource('imeiautorizado', ImeiautorizadoController::class);
Route::resource('funcionariocasilla', FuncionariocasillaController::class);
Route::resource('votocandidato', VotocandidatoController::class);

app/Models/Eleccioncomite.php
<?php

/**
 * Created by Reliese Model.
 */

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Eleccioncomite
 * 
 * @property int $id
 * @property int|null $eleccion_id
 * @property int|null $funcionario_id
 * @property int|null $rol_id
 * 
 * @property Eleccion|null $eleccion
 * @property Funcionario|null $funcionario
 * @property Rol|null $rol
 *
 * @package App\Models
 */
class Eleccioncomite extends Model
{
	protected $table = 'eleccioncomite';
	public $timestamps = false;

	protected $casts = [
		'eleccion_id' => 'int',
		'funcionario_id' => 'int',
		'rol_id' => 'int'
	];

	protected $fillable = [
		'eleccion_id',
		'funcionario_id',
		'rol_id'
	];

	public function eleccion()
	{
		return $this->belongsTo(Eleccion::class);
	}

	public function funcionario()
	{
		return $this->belongsTo(Funcionario::class);
	}

	public function rol()
	{
		return $this->belongsTo(Rol::class);
	}
}

app/Http/Controllers/EleccioncomiteController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Funcionario;
use App\Models\Rol;
use App\Models\Eleccion;
use App\Models\Eleccioncomite;
use Illuminate\Support\Facades\DB;
use Barryvdh\DomPDF\Facade as PDF; //--- Se agregó esta línea

class EleccioncomiteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $sql = "SELECT ec.id, e.periodo as eleccion, f.nombrecompleto as funcionario, r.descripcion as rol
FROM eleccioncomite ec INNER JOIN eleccion e ON ec.eleccion_id = e.id
INNER JOIN funcionario f ON ec.funcionario_id = f.id
INNER JOIN rol r ON ec.rol_id = r.id";

        $eleccioncomites = DB::select($sql);
        return view("eleccioncomite/list",
            compact("eleccioncomites")); 
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Rol::all();
        $elecciones = Eleccion::all();
        $funcionarios = Funcionario::all();

        return view("eleccioncomite/create",
            compact("roles","elecciones","funcionarios"));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'rol_id' => 'required|integer',
            'funcionario_id'=>'required|integer',
            'eleccion_id'=>'required|integer'
        ]);

        $data = [
            "rol_id" => $request->rol_id ,
            "funcionario_id" => $request->funcionario_id ,
            "eleccion_id" => $request->eleccion_id
        ];

        Eleccioncomite::create($data);
        return redirect('eleccioncomite')->with('success',
            ' guardado satisfactoriamente ...');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $roles = Rol::all();
        $elecciones = Eleccion::all();
        $funcionarios = Funcionario::all();

        $eleccioncomite = Eleccioncomite::find($id);
        
        return view('eleccioncomite/edit',compact("eleccioncomite","roles","elecciones","funcionarios"));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'rol_id' => 'required|integer',
            'funcionario_id'=>'required|integer',
            'eleccion_id'=>'required|integer'
        ]);

        $data = [
            "rol_id" => $request->rol_id ,
            "funcionario_id" => $request->funcionario_id ,
            "eleccion_id" => $request->eleccion_id
        ];

        Eleccioncomite::whereId($id)->update($data);
        return redirect('eleccioncomite')
        ->with('success', 'Actualizado correctamente...');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $eleccioncomite = Eleccioncomite::find($id);
        $eleccioncomite->delete();
        return redirect('eleccioncomite');
    }

    public function generatepdf()
    {
  
$sql = "SELECT ec.id, e.periodo as eleccion, f.nombrecompleto as funcionario, r.descripcion as rol
FROM eleccioncomite ec INNER JOIN eleccion e ON ec.eleccion_id = e.id
INNER JOIN funcionario f ON ec.funcionario_id = f.id
INNER JOIN rol r ON ec.rol_id = r.id";

        $eleccioncomites = DB::select($sql);

      // print_r($casillas);
        $pdf = PDF::loadView('eleccioncomite/vista', ['eleccioncomites'=>$eleccioncomites]);
        return $pdf->stream('eleccioncomite.pdf');
    }
}

resources/views/eleccioncomite/create.blade.php
@extends('plantilla')
@section('content')
<style>
	.uper {
		margin-top: 40px;
	}
</style>
<div class="card uper">
	<div class="card-header">
	Agregar Eleccion Comite
</div>
<div class="card-body">
	@if ($errors->any())
	<div class="alert alert-danger">
		<ul>
			@foreach ($errors->all() as $error)
			<li>{{ $error }}</li>
		@endforeach
	</ul>
</div><br/>
@endif
<form method="post" action="{{ route('eleccioncomite.store') }} " enctype="multipart/form-data">
	{{ csrf_field() }}

	<div class="form-group">
		@csrf
		<label for="eleccion">Eleccion:</label>
		<select name="eleccion_id">
			@foreach ($elecciones as $eleccion)
			<option value="{{$eleccion->id}}">{{$eleccion->periodo}}</option>
			@endforeach
		</select>
	</div>

	<div class="form-group">
		@csrf
		<label for="funcionario">Funcionario:</label>
		<select name="funcionario_id">
			@foreach ($funcionarios as $funcionario)
			<option value="{{$funcionario->id}}">{{$funcionario->nombrecompleto}}</option>
			@endforeach
		</select>
	</div>

	<div class="form-group">
		@csrf
		<label for="rol">Rol:</label>
		<select name="rol_id">
			@foreach ($roles as $rol)
			<option value="{{$rol->id}}">{{$rol->descripcion}}</option>
			@endforeach
		</select>
	</div>

	<button type="submit" class="btn btn-primary">Guardar</button>
</form>
</div>
</div>
@endsection

resources/views/eleccioncomite/edit.blade.php
@extends('plantilla')
@section('content')
<style>
	.uper {
		margin-top: 40px;
	}
</style>
<div class="card uper">
	<div class="card-header">	Editar Eleccion Comite </div>
	<div class="card-body">
		@if ($errors->any())
		<div class="alert alert-danger">
			<ul>
				@foreach ($errors->all() as $error)
				<li>{{ $error }}</li>
			@endforeach
		</ul>
	</div><br />
	@endif
	<form method="POST" action="{{ route('eleccioncomite.update', $eleccioncomite->id) }}"
		enctype="multipart/form-data">
		{{ csrf_field() }}
		@method('PUT')

		<div class="form-group">
			@csrf
			<label for="id">ID:</label>
			<input type="text" 
			class="form-control" 
			readonly="true" 
			value="{{$eleccioncomite->id}}"
			name="id"/>
		</div>

	<div class="form-group">
		@csrf
		<label for="eleccion">Eleccion:</label>
		<select name="eleccion_id">
			@foreach ($elecciones as $eleccion)
			  @php
			      $selected = ($eleccioncomite->eleccion_id==$eleccion->id)?" selected":"";
			  @endphp
			<option value="{{$eleccion->id}}" {{$selected}}>{{$eleccion->periodo}}</option>
			@endforeach
		</select>
	</div>
  
	<div class="form-group">
		@csrf
		<label for="funcionario">Funcionario:</label>
		<select name="funcionario_id">
			@foreach ($funcionarios as $funcionario)
			  @php
			      $selected = ($eleccioncomite->funcionario_id==$funcionario->id)?" selected":"";
			  @endphp
			<option value="{{$funcionario->id}}" {{$selected}}>{{$funcionario->nombrecompleto}}</option>
			@endforeach
		</select>
	</div>

		<div class="form-group">
		@csrf
		<label for="rol">Rol:</label>
		<select name="rol_id">
			@foreach ($roles as $rol)
			  @php
			      $selected = ($eleccioncomite->rol_id==$rol->id)?" selected":"";
			  @endphp
			<option value="{{$rol->id}}" {{$selected}}>{{$rol->descripcion}}</option>
			@endforeach
		</select>
	</div>


		<button type="submit" class="btn btn-primary">Guardar</button>
	</form>
</div>
</div>
@endsection

resources/views/eleccioncomite/list.blade.php
@extends('plantilla')
@section('content')
<style>
	.uper {
		margin-top: 40px;
	}
</style>

<br>
<br>
<h1 align="center">ELECCION COMITE</h1>
<br>

<div class="uper">
	@if(session()->get('success'))
	<div class="alert alert-success">
		{{ session()->get('success') }}
	</div><br />
	@endif
	<table class="table table-striped">
		<thead>
			<tr>
				<th>ID</th>
				<th>PERIODO DE ELECCION</th>
				<th>FUNCIONARIO</th>
				<th>ROL</th>
				<th colspan="2">Action</th>
			</tr>
		</thead>
		<tbody>
			@foreach($eleccioncomites as $eleccioncomite)
			<tr>
				<td>{{$eleccioncomite->id}}</td>
				<td>{{$eleccioncomite->eleccion}}</td>
                <td>{{$eleccioncomite->funcionario}}</td>
                <td>{{$eleccioncomite->rol}}</td>

				<td><a href="{{ route('eleccioncomite.edit', $eleccioncomite->id)}}"
					class="btn btn-primary">Edit</a></td>
				<td>	
					<form action="{{ route('eleccioncomite.destroy', $eleccioncomite->id)}}" method="post">
						@csrf
						@method('DELETE')
						<button class="btn btn-danger" type="submit"
						onclick="return confirm('Esta seguro de borrar a {{$eleccioncomite->funcionario}} con rol de {{$eleccioncomite->rol}}')" >Del</button>
					</form>
				</td>
			</tr>
		@endforeach
	</tbody>
</table>
<div>
@endsection

resources/views/eleccioncomite/vista.blade.php
<!DOCTYPE HTML>
<HTML>
<head>
	<div style='text-align:center;'>	
   
		<h1>PDF generado desde etiquetas html:</h1>
		<h2> Eleccion Comite</h2>
		<br>
</head>
   
   </div>
   <BODY>

    <table class="table table-striped" align="center"  width="90%"  border="1" align="center" cellspacing="0">
		<thead>
			<tr>
				<th align="center">ID</th>
				<th align="center">PERIODO DE ELECCION</th>
				<th align="center">FUNCIONARIO</th>
				<th align="center">ROL</th>
				
			</tr>
		</thead>
		<tbody>
			@foreach($eleccioncomites as $eleccioncomite)
			<tr> 
				<td align="center">{{$eleccioncomite->id}}</td>
				<td>{{$eleccioncomite->eleccion}}</td>
                <td>{{$eleccioncomite->funcionario}}</td>
                <td>{{$eleccioncomite->rol}}</td>
			</tr>
		@endforeach
	</tbody>
</table>

<div>
	<div style='text-align:center;'>	
   
   		<h3>&copy;Wendy.dev</h3> 
</div>
<script type="text/php">
		if (isset($pdf) ) {
				$pdf->page_script('
				$font = $fontMetrics->get_font("Arial, Helvetica, sans-serif", "normal");
				$pdf->text(270, 730, "Pagina $PAGE_NUM de $PAGE_COUNT", $font, 10);
				');
		}
</script>
   </BODY>
</HTML>