routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\CasillaController;
use App\Http\Controllers\CandidatoController;
use App\Http\Controllers\FuncionarioController;
use App\Http\Controllers\RolController;
use App\Http\Controllers\EleccionController;
use App\Http\Controllers\EleccioncomiteController;
use App\Http\Controllers\VotoController;
use App\Http\Controllers\ImeiautorizadoController;
use App\Http\Controllers\FuncionariocasillaController;
use App\Http\Controllers\VotocandidatoController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

//PDF TABLAS
Route::get('casilla/pdf', [CasillaController::class, 'generatepdf']);
Route::get('candidato/pdf', [CandidatoController::class, 'generatepdf']);
Route::get('eleccion/pdf', [EleccionController::class, 'generatepdf']);
Route::get('funcionario/pdf', [FuncionarioController::class, 'generatepdf']);
Route::get('rol/pdf', [RolController::class, 'generatepdf']);
Route::get('eleccioncomite/pdf', [EleccioncomiteController::class, 'generatepdf']);
Route::get('voto/pdf', [VotoController::class, 'generatepdf']);
Route::get('imeiautorizado/pdf', [ImeiautorizadoController::class, 'generatepdf']);
Route::get('funcionariocasilla/pdf', [FuncionariocasillaController::class, 'generatepdf']);
Route::get('votocandidato/pdf', [VotocandidatoController::class, 'generatepdf']);

//GRAFICAS
Route::get('votocandidato/chart', [VotocandidatoController::class, 'generatechart']);
Route::get('funcionario/chart', [FuncionarioController::class, 'generatechart']);
Route::get('candidato/chart', [CandidatoController::class, 'generatechart']);


//CONTROLLERS
Route::resource('casilla', CasillaController::class);
Route::resource('candidato', CandidatoController::class);
Route::resource('funcionario', FuncionarioController::class);
Route::resource('rol', RolController::class);
Route::resource('eleccion', EleccionController::class);
Route::resource('eleccioncomite', EleccioncomiteController::class);
Route::resource('voto', VotoController::class);
Route::resource('imeiautorizado', ImeiautorizadoController::class);
Route::resource('funcionariocasilla', FuncionariocasillaController::class);
Route::resource('votocandidato', VotocandidatoController::class);

app/Models/Eleccion.php
<?php

/**
 * Created by Reliese Model.
 */

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;

/**
 * Class Eleccion
 * 
 * @property int $id
 * @property string $periodo
 * @property Carbon|null $fecha
 * @property Carbon|null $fechaapertura
 * @property Carbon|null $horaapertura
 * @property Carbon|null $fechacierre
 * @property Carbon|null $horacierre
 * @property string|null $observaciones
 * 
 * @property Collection|Eleccioncomite[] $eleccioncomites
 * @property Collection|Funcionariocasilla[] $funcionariocasillas
 * @property Collection|Imeiautorizado[] $imeiautorizados
 * @property Collection|Voto[] $votos
 *
 * @package App\Models
 */
class Eleccion extends Model
{
	protected $table = 'eleccion';
	public $timestamps = false;

	protected $dates = [
		'fecha',
		'fechaapertura',
		'horaapertura',
		'fechacierre',
		'horacierre'
	];

	protected $fillable = [
		'periodo',
		'fecha',
		'fechaapertura',
		'horaapertura',
		'fechacierre',
		'horacierre',
		'observaciones'
	];

	public function eleccioncomites()
	{
		return $this->hasMany(Eleccioncomite::class);
	}

	public function funcionariocasillas()
	{
		return $this->hasMany(Funcionariocasilla::class);
	}

	public function imeiautorizados()
	{
		return $this->hasMany(Imeiautorizado::class);
	}

	public function votos()
	{
		return $this->hasMany(Voto::class);
	}
}

app/Http/Controllers/Api/EleccionController.php
<?php

namespace App\Http\Controllers\Api;

namespace App\Http\Controllers\Api;
use App\Http\Controllers\Api\GenericController as GenericController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use App\Models\Eleccion;

class EleccionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $elecciones = Eleccion::all();
        $resp = $this->sendResponse($elecciones, "Listado de Elecciones");
        return ($resp);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validacion = Validator::make($request->all(), [
            'periodo' => 'unique:Eleccion|required|max:100',
            'observaciones'=> 'required|max:200',
            'horaapertura' =>'required',
            'horacierre' =>'required'
        ]);

        $campos = array(
            'periodo' => $request->periodo,
            'observaciones' => $request->observaciones,
            'horaapertura' => $request->horaapertura,
            'horacierre' => $request->horacierre

        );

        $eleccion = Eleccion::create($campos);
        $resp = $this->sendResponse($eleccion,
            "Guardado...");
        return($resp);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/EleccionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Eleccion;
use Barryvdh\DomPDF\Facade as PDF; //--- Se agregó esta línea

class EleccionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
         $elecciones = Eleccion::all();
        return view('eleccion/list', compact('elecciones'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
         return view('eleccion/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'periodo'=> 'required|max:200',
            'fecha'=>'required',
            'fechaapertura'=>'required|date',
            'horaapertura'=>'required',
            'fechacierre'=>'required',
            'horacierre' =>'required',
            'observaciones' =>'required|max:200'
        ]);

         $data = [
           "periodo"=> $request->periodo,
           "fecha" => $request->fecha,
           "fechaapertura"=>$request->fechaapertura,
           "horaapertura"=>$request->horaapertura,
           "fechacierre" => $request->fechacierre,
           "horacierre" => $request->horacierre,
           "observaciones" => $request->observaciones
       ];

        $eleccion = Eleccion::create($data);
        return redirect('eleccion')->with('success',
        $eleccion->periodo . ' guardado satisfactoriamente ...');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
         $eleccion = Eleccion::find($id);
        return view('eleccion/edit',compact('eleccion'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'periodo'=> 'required|max:200',
            'fecha'=>'required',
            'fechaapertura'=>'required|date',
            'horaapertura'=>'required',
            'fechacierre'=>'required',
            'horacierre' =>'required',
            'observaciones' =>'required|max:200'
        ]);

         $data = [
           "periodo"=> $request->periodo,
           "fecha" => $request->fecha,
           "fechaapertura"=>$request->fechaapertura,
           "horaapertura"=>$request->horaapertura,
           "fechacierre" => $request->fechacierre,
           "horacierre" => $request->horacierre,
           "observaciones" => $request->observaciones
       ];

        Eleccion::whereId($id)->update($data);
        return redirect('eleccion')
        ->with('success', 'Actualizado correctamente...');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $eleccion = Eleccion::find($id);
        $eleccion->delete();
        return redirect('eleccion');
    }

    public function generatepdf()
    {
  
       $elecciones = Eleccion::all();
      // print_r($casillas);
        $pdf = PDF::loadView('eleccion/vista', ['elecciones'=>$elecciones]);
        return $pdf->stream('eleccion.pdf');
    }

  
}

resources/views/eleccion/create.blade.php
@extends('plantilla')
@section('content')
<style>
	.uper {
		margin-top: 40px;
	}
</style>
<div class="card uper">
	<div class="card-header">
	Agregar Eleccion
</div>
<div class="card-body">
	@if ($errors->any())
	<div class="alert alert-danger">
		<ul>
			@foreach ($errors->all() as $error)
			<li>{{ $error }}</li>
		@endforeach
	</ul>
</div><br />
@endif
<form method="post" action="{{ route('eleccion.store') }} " enctype="multipart/form-data">
	{{ csrf_field() }}
	<div class="form-group">
		@csrf
		<label for="periodo">Periodo:</label>
		<input type="text" class="form-control" 
		 maxlength="100" 
		 name="periodo" id="periodo"/>
	</div>
		
	<div class="form-group">
		@csrf
		<label for="fecha">Fecha:</label>
		<input type="date" 
		class="form-control"
		step="1" min="2013-01-01" 
		max="2100-12-31" 
		value="<?php echo date("Y-m-d");?>"
		name="fecha" id="fecha"/>
	</div>

	<div class="form-group">
		@csrf
		<label for="fechaapertura">Fecha Apertura:</label>
		<input type="date" 
		class="form-control"
		step="1" min="2013-01-01" 
		max="2100-12-31" 
		value="<?php echo date("Y-m-d");?>"
		name="fechaapertura" id="fechaapertura" />
	</div>

	<div class="form-group">
		@csrf
		<label for="horaapertura">Hora Apertura:</label>
		<input type="time" 
		class="form-control"
		name="horaapertura" id="horaapertura"/>
	</div>

	<div class="form-group">
		@csrf
		<label for="fechacierre">Fecha Cierre :</label>
		<input type="date" 
		class="form-control"
		step="1" min="2013-01-01" 
		max="2100-12-31" 
		value="<?php echo date("Y-m-d");?>"
		name="fechacierre" id="fechacierre"/>
	</div>

	<div class="form-group">
		@csrf
		<label for="horacierre">Hora Cierre:</label>
		<input type="time" 
		class="form-control"
		name="horacierre" id="horacierre"/>
	</div>

	<div class="form-group">
		@csrf
		<label for="observaciones">Observaciones:</label>
		<input type="text" class="form-control" 
		 maxlength="100" 
		 name="observaciones" id="observaciones"/>
	</div>

	<button type="submit" class="btn btn-primary"onClick="return validate ()">Guardar</button>

</form>
</div>
</div>
@endsection

@section('page-script')
    <script type="text/javascript" src="/js/eleccion.js"></script>
@stop

resources/views/eleccion/edit.blade.php
@extends('plantilla')
@section('content')
<style>
	.uper {
		margin-top: 40px;
	}
</style>
<div class="card uper">
	<div class="card-header">	Editar Eleccion </div>
	<div class="card-body">
		@if ($errors->any())
		<div class="alert alert-danger">
			<ul>
				@foreach ($errors->all() as $error)
				<li>{{ $error }}</li>
			@endforeach
		</ul>
	</div><br />
	@endif
	<form method="POST" action="{{ route('eleccion.update', $eleccion->id) }}"
		enctype="multipart/form-data">
		{{ csrf_field() }}
		@method('PUT')

		<div class="form-group">
			@csrf
			<label for="id">ID:</label>
			<input type="text" 
			class="form-control" 
			readonly="true" 
			value="{{$eleccion->id}}"
			name="id"/>
		</div>

		<div class="form-group">
			@csrf
			<label for="periodo">Eleccion:</label>
			<input type="text" 
			value="{{$eleccion->periodo}}" 
			class="form-control" 
			name="periodo"/>
		</div>

		<div class="form-group">
			@csrf
			<label for="fecha">Fecha:</label>
			<input type="date" 
			class="form-control"
			step="1" min="1910-01-01" 
			max="2100-12-31" 
			value="<?php echo date("Y-m-d");?>" 
			name="fecha" >
		</div>

          <div class="form-group">
          	@csrf
          	<label for="fechaapertura">Fecha Apertura:</label>
          	<input type="date" 
          	class="form-control"
          	step="1" min="1910-01-01" 
          	max="2100-12-31" 
          	value="<?php echo date("Y-m-d");?>"
          	name="fechaapertura" >
          </div>

          <div class="form-group">
          	@csrf
          	<label for="horaapertura">Hora Apertura:</label>
          	<input type="time" 
          	class="form-control"
          	name="horaapertura">
          </div>

          <div class="form-group">
          	@csrf
          	<label for="fechacierre">Fecha Cierre :</label>
          	<input type="date" 
          	class="form-control"
          	step="1" min="2013-01-01" 
          	max="2100-12-31" 
          	value="<?php echo date("Y-m-d");?>"
          	name="fechacierre" >
          </div>

          <div class="form-group">
          	@csrf
          	<label for="horacierre">Hora Cierre:</label>
          	<input type="time" 
          	class="form-control"
          	name="horacierre">
          </div>

          <div class="form-group">
			@csrf
			<label for="observaciones">Observaciones:</label>
			<input type="text" 
			value="{{$eleccion->observaciones}}" 
			class="form-control" 
			name="observaciones"/>
		 </div>

		<button type="submit" class="btn btn-primary">Guardar</button>
	</form>
</div>
</div>
@endsection

resources/views/eleccion/list.blade.php
@extends('plantilla')
@section('content')
<style>
	.uper {
		margin-top: 40px;
	}
</style>

<br>
<br>
<h1 align="center">ELECCION</h1>
<br>

<div class="uper">
	@if(session()->get('success'))
	<div class="alert alert-success">
		{{ session()->get('success') }}
	</div><br />
	@endif
	<table class="table table-striped">
		<thead>
			<tr>
				<td>ID</td>
				<td>PERIODO</td>
				<td>FECHA</td>
				<td>FECHA DE APERTURA</td>
				<td>HORA DE APERTURA</td>
				<td>FECHA DE CIERRE</td>
				<td>HORA DE CIERRE</td>
				<td>OBSERVACIONES</td>
				<td colspan="2">Action</td>
			</tr>
		</thead>
		<tbody>
			@foreach($elecciones as $eleccion)
			<tr>
				<td>{{$eleccion->id}}</td>
				<td>{{$eleccion->periodo}}</td>
                <td>{{$eleccion->fecha}}</td>
                <td>{{$eleccion->fechaapertura}}</td>
                <td>{{$eleccion->horaapertura}}</td>
                <td>{{$eleccion->fechacierre}}</td>
                <td>{{$eleccion->horacierre}}</td>
                <td>{{$eleccion->observaciones}}</td>

				<td><a href="{{ route('eleccion.edit', $eleccion->id)}}"
					class="btn btn-primary">Edit</a></td>
				<td>	
					<form action="{{ route('eleccion.destroy', $eleccion->id)}}" method="post">
						@csrf
						@method('DELETE')
						<button class="btn btn-danger" type="submit"
						onclick="return confirm('Esta seguro de borrar {{$eleccion->periodo}}')" >Del</button>
					</form>
				</td>
			</tr>
		@endforeach
	</tbody>
</table>
<div>
@endsection

resources/views/eleccion/vista.blade.php
<!DOCTYPE HTML>
<HTML>
<head>
	<div style='text-align:center;'>	
   
		<h1>PDF generado desde etiquetas html:</h1>
		<h2> Elecccion</h2>
		<br>
</head>
   
   </div>
   <BODY>

      <table class="table table-striped" align="center"  width="100%"  border="1" align="center" cellspacing="0">
		<thead>
			<tr>
				<td align="center">ID</td>
				<td align="center">PERIODO</td>
				<td align="center">FECHA</td>
				<td align="center">FECHA DE APERTURA</td>
				<td align="center">HORA DE APERTURA</td>
				<td align="center">FECHA DE CIERRE</td>
				<td align="center">HORA DE CIERRE</td>
				<td align="center">OBSERVACIONES</td>
			</tr>
		</thead>
		<tbody>
			@foreach($elecciones as $eleccion)
			<tr>
				<td>{{$eleccion->id}}</td>
				<td>{{$eleccion->periodo}}</td>
                <td>{{$eleccion->fecha}}</td>
                <td>{{$eleccion->fechaapertura}}</td>
                <td>{{$eleccion->horaapertura}}</td>
                <td>{{$eleccion->fechacierre}}</td>
                <td>{{$eleccion->horacierre}}</td>
                <td>{{$eleccion->observaciones}}</td>
			</tr>
		@endforeach
	</tbody>
</table>

<div>
	<div style='text-align:center;'>	
   
   		<h3>&copy;Wendy.dev</h3> 
</div>
<script type="text/php">
		if (isset($pdf) ) {
				$pdf->page_script('
				$font = $fontMetrics->get_font("Arial, Helvetica, sans-serif", "normal");
				$pdf->text(270, 730, "Pagina $PAGE_NUM de $PAGE_COUNT", $font, 10);
				');
		}
</script>
   </BODY>
</HTML>